nameOverride: ""
fullnameOverride: ""

admin:
  image:
    repository: aaronshaf/dynamodb-admin
    tag: latest
    pullPolicy: IfNotPresent
    env:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      DYNAMO_ENDPOINT: http://localhost:8000
  container:
    port: 8001
  service:
    type: ClusterIP
    port: 8001

