nameOverride: ""
fullnameOverride: ""

dynamodb:
  image:
    repository: amazon/dynamodb-local
    tag: latest
    pullPolicy: IfNotPresent
    env:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      DYNAMO_ENDPOINT: http://localhost:8000
  container:
    port: 8000
  service:
    type: ClusterIP
    port: 8000

