apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamodb.fullname" . }}
  labels:
    {{- include "dynamodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dynamodb.service.type }}
  selector:
    {{- include "dynamodb.selectorLabels" . | nindent 4 }}
  ports:
  - name: app-port
    protocol: TCP
    port: {{ .Values.dynamodb.service.port }}
    targetPort: {{ .Values.dynamodb.container.port }}