apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynamodb-admin.fullname" . }}
  labels:
    {{- include "dynamodb-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.admin.service.type }}
  selector:
    {{- include "dynamodb-admin.selectorLabels" . | nindent 4 }}
  ports:
  - name: app-port
    protocol: TCP
    port: {{ .Values.admin.service.port }}
    targetPort: {{ .Values.admin.container.port }}